version: "3.7"

services:
  leaf-portal-php-8:
    image: leaf-fpm
    container_name: leaf-fpm
    env_file: 
      - ./env_files/globals_local.env
      - ./env_files/secrets.env
    build:
      context: ../
      dockerfile: docker/php/leaf_monlith.dockerfile
      args:
        - BUILD_UID=${BUILD_UID}
        - SMTP_HOST=smtp.leaf-portal
        - MAIL_HUB=smtp.leaf-portal
    volumes:
      # - ../launchpad:/var/www/html/launchpad  # Dev should echo prod as exact as possible.  Will be added later
      - ../LEAF_Nexus:/var/www/html/LEAF_Nexus
      - ../LEAF_Request_Portal:/var/www/html/LEAF_Request_Portal
      - ../health_checks:/var/www/html/health_checks
      # - ../libs:/var/www/html/libs  # temp step.  Will shift to below later
      # - leaf-lib:/var/www/html/libs
      # - ../test:/var/www/html/test
      # - ../test_server:/var/www/html/test_server
      # - ./docker/php/conf.d/xdebug.ini  # Not sure what this is even for.
    networks:
      # - traefik
      - leaf-sql
      - leaf
    environment:
      - REMOTE_USER=${REMOTE_USER}
      - APACHE_RUN_USER=build_user

  leaf-nginx:
    image: leaf-nginx
    container_name: leaf-nginx
    build:
      context: ../
      dockerfile: docker/nginx/leaf_nginx.dockerfile
    volumes:
      # - ./nginx/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9080:8080
    networks:
      - traefik
      - leaf    
    labels:          
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.leaf_8.loadbalancer.server.port=8080"
      - "traefik.http.routers.leaf_8.rule=Host(`leaf-8.dev.vovina-tisa.net`)"
      - "traefik.http.routers.leaf_8.entrypoints=web, web-secure"
      - "traefik.http.routers.leaf_8.tls.certresolver=dev_http"
    

  smtp.leaf-portal:
    image: pelentan/fake-smtp:1.0
    container_name: leaf_smtp
    env_file: 
      - ./env_files/globals_local.env
      - ./env_files/secrets.env
    ports:
      - "2525:25" # smtp port
      # - "5080:5080" # web ui port
    restart: 'always'
    networks:
      - traefik
      - leaf    
    labels:          
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.leaf_smtp.loadbalancer.server.port=5080"
      - "traefik.http.routers.leaf_smtp.rule=Host(`smtp.dev.vovina-tisa.net`)"
      - "traefik.http.routers.leaf_smtp.entrypoints=web, web-secure"
      - "traefik.http.routers.leaf_smtp.tls.certresolver=dev_http"

  leaf_adminer:
    container_name: leaf_adminer
    image: adminer
    ports:
      - 3388:8080
    networks:
      - traefik
      - leaf-sql
    labels:          
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.services.leaf_adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.leaf_adminer.rule=Host(`leaf-adminer.dev.vovina-tisa.net`)"
      - "traefik.http.routers.leaf_adminer.entrypoints=web, web-secure"
      - "traefik.http.routers.leaf_adminer.tls.certresolver=dev_http"

  mysql.leaf-portal:
    image: pelentan/leaf-mysql:2.0
    container_name: mysql.leaf-portal
    env_file: 
      - ./env_files/mysql_local.env
      - ./env_files/secrets.env
    restart: 'always'
    networks:
      - leaf-sql
    volumes:
      - leaf-mysql-data:/var/lib/mysql

volumes:
  leaf-php-data:
    external: true
  leaf-lib:
    external: true
  leaf-mysql-data:
    external: false

networks:
  leaf-sql:
    external: true
  traefik:
    external: true
  leaf:
    external: true
    




 

