name: Java-Maven CI

on:
  schedule:
  - cron:  '*/10 * * * *'    # At every 10th minute (every 5 is minimum...)
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'    
    - name: setup Chrome
      run:   |
              chmod +x ./scripts/InstallChrome.sh
              ./scripts/InstallChrome.sh:
    - name: Build with Maven
      run: mvn test --file pom.xml
