name: Automated PROD Monitoring
# every step must define a `uses` or `run` key
on:
  # workflow_dispatch:
  # schedule: every 10 minutes
    # To get CST in Summer, add 5 hours to get UTC time
    # - cron:  '30 5 * * * '   # uses UTC time - currently set to 1:30am EST (using UTC values)
  schedule:
    - cron:  '*/10 * * * *'    # At every 10th minute
    # - cron:  '45 20 * * * '     # uses UTC time - currently set to 3:30pm CST (using UTC values)
  pull_request:
    branches: [ Master ]
    
  workflow_dispatch:

jobs:
  build:
    # name: CI-Automation
    runs-on: ubuntu-latest
    # a step cannot have both the `uses` and `run` keys
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1     # was v2
      with:
        java-version: '1.8'
        # distribution: 'adopt'
    - name: setup Chrome
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh:
    - name: Build with Maven
      # run: mvn clean test
      run: mvn test --file pom.xml