---
# This is a basic workflow to help you get started with Actions

name: Toga

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - 'aws-ecs-prototype'
    paths:
      - 'LEAF_Nexus/**'
      - 'LEAF_Request_Portal/**'
      - 'libs/**'
      - '.github/workflows/toga_workflow.yml'
  pull_request:
    branches: 
      - 'aws-ecs-prototype'
    paths:
      - '.LEAF_Nexus/**'
      - '.LEAF_Request_Portal/**'
      - '.libs/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v2

      - name: Docker Build X
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        uses: actions/cache@v2.1.6
        with: 
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        if: github.event != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   if: github.event != 'pull_request'
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta Data
        id: docker_meta
        uses: docker/metadata-action@v3.3.0
        with: 
          images: |
            the_image_tag_for_docker_repository
            the_image_tag_for_github_repository 
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: docker/php
          dockerfile: leaf_monlith.dockerfile
          # args:
          #   - BUILD_UID=1000
          #   - SMTP_HOST=smtp.leaf-portal
          #   - MAIL_HUB=smtp.leaf-portal
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels}}

      - name: Digest of build
        run: echo ${{ steps.docker_build.outputs.digest }}


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
